# Generated by Django 5.0.7 on 2026-03-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Tallas o medidas disponibles, separadas por coma. Ej: S, M, L o 38, 40, 42', max_length=255),
        ),
    ]
