# Generated by Django 5.0.7 on 2026-03-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_cartitem_size_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(help_text='Precio en Guaraníes (sin decimales)'),
        ),
    ]
